services:
  agent-api:
    container_name: sahiloan-chatbot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - sahiloan-chatbot-network

volumes:
  data:

networks:
  sahiloan-chatbot-network:
    name: sahiloan-chatbot-network